// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'context': string;
  'deleteID': string;
  'deleteQuestion': string;
  'duplicate': string;
  'header': string;
  'id': string;
  'languageSelector': string;
  'marked': string;
  'modal': string;
  'modalClose': string;
  'modalContent': string;
  'modalHeader': string;
  'modalTitle': string;
  'output': string;
  'parent': string;
  'question': string;
  'status': string;
}
declare var cssExports: CssExports;
export = cssExports;
